server:
  port: 8080
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/catsitter-manager
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  defer-datasource-initialization: true
my:
  upload_location: Uploads
