spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catsitter-manager
    username: dgeurts
    password: M@ud2009
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect